ErrorException: `a ? b : c ? d : e` is deprecated.
Uncaught ErrorException: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Error on PHP 7.4